### ISSUE TITLE
Error message on failed startup

### ISSUE THREAD

**Issue by uv48uson** [pardinensis/Outdraft#2]
As a user i want to get a warning or error message whenever the tools fails to start. This might be due to a missing data folder for example.
The error message should show the ocurred problem. If the tool fails completely a stacktrace might be helpful as well.
The message should help the user to understand the problem and fix it by for example redownloading the data folder. Additionally a stacktrace might help the developer to reproduce the error.

**Comment by pardinensis** [comment]
fixed in 551634eccae8e4e0d559547667d3a8f7a0765fd7
The program now shows an error message suggesting to place the jar file next to the data folder.

> If the tool fails completely a stacktrace might be helpful as well.

The most common reason for a failed startup is that the initialization of the heroes failes because of missing or misplaced data files. A stacktrace does not help at this point. I may refine the error message though as it is currently very generic.

> and fix it by for example redownloading the data folder.

Not possible. The data is split into two subgroups: cache and config. The cache can and will be redownloaded if missing but the config files cannot.
